extend schema
@link(url: "https://specs.apollo.dev/federation/v2.1",
  import: ["@key", "@shareable", "@tag", "@inaccessible", "@composeDirective", "@requires", "@external"])

type Query {
  subscriberByPhoneNumber(
    phoneNumber: ID!
  ): SubscriberResponse
}

union SubscriberResponse =  Subscriber | SubscriberError

type Subscriber @key(fields: "phoneNumber") {
  """Subscriber Phone Number, often refered as MSISDN"""
  phoneNumber: ID!

  """Full Name flatten (first, middle and last name flatten)"""
  nickName: String
  """First name of the individual"""
  firstName: String!
  """Family name of the individual. Contains the non-chosen or inherited name. Also known as last name in the Western context"""
  lastName: String!
}

interface Error {
  """A succinct, domain-specific human-readable text string or http-code to identify the type of error for the given status code"""
  code: String!
  """A human-readable message describing the error"""
  message: String!
}

type SubscriberError implements Error @shareable {
  """A succinct, domain-specific human-readable text string or http-code to identify the type of error for the given status code"""
  code: String!
  """A human-readable message describing the error"""
  message: String!
}
